<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.min.js"></script>


<div class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2" style="margin-top:50px;" id="loginbox">
	<div class="panel panel-info">
		<div class="panel-heading">
			<div class="panel-title">Forgot Password?</div>
			<div style="float:right; font-size: 80%; position: relative; top:-10px"><a title="Go back to Login"
			                                                                           href="<?php echo $this->url
				('user', array
				('action'=>'login'));?>">Login</a></div>
		</div>

		<div class="panel-body" style="padding-top:30px">

			<div class="alert alert-danger col-sm-12" id="login-alert" style="display:none"></div>


			<?php
				$form->prepare();

				$form->setAttribute('class', 'form-horizontal');
				$form->setAttribute('role', 'form');
				echo $this->form()->openTag($form);
			?>

			<div class="input-group" style="margin-bottom: 25px">
				<span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
				<?php
					echo $this->formRow($form->get('username'));
				?>
			</div>


			<div class="form-group" style="margin-top:10px">
				<!-- Button -->

				<div class="col-sm-12 controls">

					<?php
						$form->get('token')->setAttribute('value',$token);
						echo $this->formHidden($form->get('token'));

						$form->get('url')->setAttribute('value',0);
						echo $this->formHidden($form->get('url'));

						echo $this->formReset($form->get('reset'));
						$form->get('submit')->setAttribute('title','Click to send password to email');
						echo $this->formSubmit($form->get('submit'));
						//@TODO Find solution to render the button in the view JT 2/27
						//echo $this->formButton($form->get('facebook'));ß


					?>


				</div>
			</div>


			<div class="form-group">
				<div class="col-md-12 control">
					<div style="border-top: 1px solid#888; padding-top:15px; font-size:85%">
						Don't have an account!
						<a href="#">
							Sign Up Here
						</a>
					</div>


				</div>
			</div>
			<?php
				echo $this->form()->closeTag();
			?>


		</div>
	</div>
</div>
