<?php echo $this->doctype(); ?>

<html lang="en">
<head>
	<meta charset="utf-8">
	<?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

	<?php echo $this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>




	<!-- Le styles -->
	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
		->prependStylesheet($this->basePath('css/style.css'))
		->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
		->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

	<!-- Scripts -->
	<?php echo $this->headScript()
		->prependFile($this->basePath('js/bootstrap.min.js'))
		->prependFile($this->basePath('js/jquery.min.js'))
		->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
		->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))

	; ?>

	<style type="text/css">
		.navbar-inverse{
			background: #353a0a;
			}
		.mylogo{
			width: 255px;
			height: 60px;;
			}
	</style>



</head>
<body>

<div class="container">

	<?php
		$flash = $this->flashMessenger();
		$flash->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
			->setMessageSeparatorString('</li><li>')
			->setMessageCloseString('</li></ul></div>');

		echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
		echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
		echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
		echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
	?>



	<?php echo $this->content; ?>

</div> <!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
